.\" @(#)cjp2k1 2010/07/02 NIST
.\" I Image Group
.\"
.TH CJP2K 1G "02 July 2010" "NIST" "NBIS Reference Manual"
.SH NAME
cjp2k \- Compress RAW image into JPEG2000 image format. This is based on the image_to_j2k application implemented in the OPENJPEG library.
.br
.SH DESCRIPTION
.B Cjp2k
takes as input a file containing a RAW grayscale fingerprint image, compresses it into a JPEG2000 image format, and writes to a new file.  This is an implementation of the JPEG 2000 standard for compression of image files.  Go to \fIhttp://www.openjpeg.org\fR for the full details on how to use the application.

.SH SEE ALSO
.BR djp2k (1G),
.BR dpyimage (1G),
.BR dwsq (1G),
.BR rdwsqcom (1G),
.BR wrwsqcom (1G)

.SH AUTHOR
NIST/ITL/DIV894/Image Group
