.\" @(#)cjpegb.1 2008/10/02 NIST
.\" I Image Group
.\" Craig Watson and Michael D. Garris
.\"
.TH CJPEGB 1G "02 October 2008" "NIST" "NBIS Reference Manual"
.SH NAME
cjpegb \- compresses a grayscale or color (RGB) image using \fIlossy\fR
Baseline JPEG (JPEGB).
.SH SYNOPSIS
.B cjpegb
.I <q=20=95>
.I <outext>
.I <image file>
.br
.RS
[\fB-raw_in \fIw\fR,\fIh\fR,\fId\fR,[\fIppi\fR]
.RS 3
[\fB-nonintrlv\fR]]
.RE
[\fIcomment file\fR]
.SH DESCRIPTION
.B Cjpegb
takes as input a file containing an uncompressed grayscale or color
(RGB) image.  Two possible input file formats are accepted, NIST IHead
files and raw pixmap files.  If a raw pixmap file is to be compressed,
then its image attributes must be provided on the command line as well.
Once read into memory, the grayscale or color pixmap is then \fIlossy\fR
compressed to a specified level of reconstruction quality using the
Independent JPEG Group's (IJG) library for Baseline JPEG (JPEGB).
The JPEGB results are then written to an output file.

Note that \fBcjpegb\fR calls the IJG library in a default color mode
where one of the compression steps includes a colorspace conversion
from RGB to YCbCr, and then the Cb & Cr component planes are
downsampled by a factor of 2 in both dimensions.  Due to this
colorspace conversion, \fBcjpegb\fR should only be used to
compress RGB color images.

The color components of RGB pixels in a raw pixmap file may
be interleaved or non-interleaved.  By default, \fBcjpegb\fR
assumes interleaved color pixels.  (See INTERLEAVE OPTIONS below.)
Regarding color pixmaps, the NIST IHead file format only supports
interleaved RGB images.

.SH OPTIONS
All switch names may be abbreviated; for example,
\fB-raw_in\fR may be written \fB-r\fR.
.TP
.I <q=20-95>
specifies the level of quality in the reconstructed image
as a result of lossy compression.  The integer quality value may
range between 20 and 95.  The lower the quality
value, the more drastic the compression.
.TP
.I <outext>
the extension of the compressed output file.
To construct the output filename, \fBcjpegb\fR takes the
input filename and replaces its extension with the one
specified here.
.TP
.I <image file>
the input file, either an IHead file or raw pixmap file,
containing the grayscale or color (RGB) image to be compressed.
.TP
\fB-raw_in \fIw\fR,\fIh\fR,\fId\fR,[\fIppi\fR]
the attributes of the input image.  This option must
be included on the command line if the input is a
raw pixmap file.
.br
.RS
.TP
.I w
the pixel width of the pixmap
.TP
.I h
the pixel height of the pixmap
.TP
.I d
the pixel depth of the pixmap
.TP
.I ppi
the optional scan resolution of the image in integer units of
pixels per inch.
.RE
.TP
.B -nonintrlv
specifies that the color components in an \fIinput\fR raw pixmap file
image are non-interleaved and stored in separate component planes.
(See INTERLEAVE OPTIONS below).
.TP
.I comment file
an optional user-supplied ASCII comment file.  (See COMMENT
OPTIONS below.)
.TP
\fB-version
\fRPrint ANSI/NIST stardand and NBIS software version.

.SH INTERLEAVE OPTIONS
The color components of RGB pixels in a raw pixmap file may
be interleaved or non-interleaved.  Color components are interleaved
when a pixel's (R)ed, (G)reen, and (B)lue components are sequentially
adjacent in the image byte stream, ie. RGBRGBRGB... .  If the color
components are non-interleaved, then all (R)ed components in the
image are sequentially adjacent in the image byte stream, followed
by all (G)reen components, and then lastly followed by all (B)lue
components.  Each complete sequence of color components is called
a \fIplane\fR.  The utilities \fBintr2not\fR and \fBnot2intr\fR
convert between interleaved and non-interleaved color components.
By default, \fBcjpegb\fR assumes interleaved
color components, and note that all color IHead images must be
interleaved.

.SH COMMENT OPTIONS
Upon successful compression, this utility generates and inserts
in the compressed output file a specially formatted comment block,
called a NISTCOM.  A NISTCOM is a text-based attribute list comprised
of (name, value) pairs, one pair per text line.
The first line of a NISTCOM always has name = "NIST_COM" 
and its value is always the total number of attributes included in
the list.  The utility \fBrdjpgcom\fR scans a JPEG compressed file for
any and all comment blocks.  Once found, the contents of each comment
block is printed to standard output.  Using this utility, the NISTCOM
provides easy access to relevant image attributes.  The following is
an example NISTCOM generated by \fBcjpegb\fR:

.RS
NIST_COM 12
.br
PIX_WIDTH 768
.br
PIX_HEIGHT 1024
.br
PIX_DEPTH 24
.br
PPI -1
.br
LOSSY 1
.br
COLORSPACE YCbCr
.br
NUM_COMPONENTS 3
.br
HV_FACTORS 2,2:1,1:1,1
.br
INTERLEAVE 1
.br
COMPRESSION JPEGB
.br
JPEGB_QUALITY 50

.RE
\fBCjpegb\fR also accepts an optional comment file on the command
line.  If provided, the contents of this file are also inserted
into the compressed output file.  If the comment file is a
NISTCOM attribute list, then its contents are merged with the
NISTCOM internally generated by \fBcjpegb\fR and a single NISTCOM
is written to the compressed output file.  Note that \fBcjpegb\fR
gives precedence to internally generated attribute values.
If the user provides a non-NISTCOM comment file,
then the contents of file are stored to a separate comment block in
the output file.  Using these comment options enables the user
to store application-specific information in a JPEG file.

.SH EXAMPLES
From \fItest/imgtools/execs/cjpegb/cjpegb.src\fR:
.PP
.RS
.B % cjpegb 50 jpb face08.raw -r 768,1024,8
.br
compresses a grayscale face image in a raw pixmap file.
.PP
.B % cjpegb 50 jpb face24.raw -r 768,1024,24
.br
compresses a color face image in a raw pixmap file.

.SH SEE ALSO
.BR cjpeg (1H),
.BR cjpegl (1G),
.BR djpegb (1G),
.BR dpyimage (1G),
.BR intr2not (1G),
.BR jpegtran (1H),
.BR not2intr (1G),
.BR rdjpgcom (1H),
.BR wrjpgcom (1H)

.SH AUTHOR
NIST/ITL/DIV894/Image Group
