.\" @(#)djp2k1 2008/10/02 NIST
.\" I Image Group
.\" Kenneth Ko
.\"
.TH DJP2K 1G "20 May 2009" "NIST" "NBIS Reference Manual"
.SH NAME
djp2k \- Decompress a JPEG2000 image into either pnm or raw image format. This is based on the j2k_to_image application implemented in the OPENJPEG library.
.br
.SH DESCRIPTION
.B Djp2k
takes as input a file containing an JPEG2000 fingerprint image, decompresses it to either pnm or raw image format, and writes to a new file.  This is an implementation of the JPEG 2000 standard for decompression of image files.  Go to \fIhttp://www.openjpeg.org\fR for the full details on how to use the application.

.SH SEE ALSO
.BR cjp2k (1G),
.BR dpyimage (1G),
.BR dwsq (1G),
.BR rdwsqcom (1G),
.BR wrwsqcom (1G)

.SH AUTHOR
NIST/ITL/DIV894/Image Group
