.\" @(#)djpegb.1 2008/10/02 NIST
.\" I Image Group
.\" Craig Watson and Michael D. Garris
.\"
.TH DJPEGB 1G "02 October 2008" "NIST" "NBIS Reference Manual"
.SH NAME
djpegb \- decompresses a Baseline JPEG (JPEGB) grayscale or color image.
.SH SYNOPSIS
.B djpegb
.I <outext>
.I <image file>
.RS 7
[\fB-raw_out\fR [\fB-nonintrlv\fR]]

.SH DESCRIPTION
.B Djpegb
takes as input a file containing a Baseline JPEG (JPEGB) compressed
grayscale or color image.  Once read into memory, the lossy-compressed
pixmap is decoded and reconstructed using the Independent JPEG Group's
(IJG) library for Baseline JPEG.  

Upon completion, two different output image file formats are possible,
a NIST IHead file (the default) or a raw pixmap file (specified by the
\fB-raw_out\fR flag).  In addition, a specially formatted text
file, called a NISTCOM, is created with extension ".ncm".  The NISTCOM
file contains relevant image attributes associated with the decoded
and reconstructed output image.
(See NISTCOM OUTPUT below.)

.SH OPTIONS
All switch names may be abbreviated; for example,
\fB-raw_out\fR may be written \fB-r\fR.
.TP
.I <outext>
the extension of the decompressed output file.
To construct the output filename, \fBdjpegb\fR takes the
input filename and replaces its extension with the one
specified here.
.TP
.I <image file>
the input JPEGB file to be decompressed.
.TP
.B -raw_out
specifies that the decoded and reconstructed image should be
stored to a raw pixmap file.
.TP
.B -nonintrlv
specifies that the color components in the reconstructed image should
be organized into separate component planes.  The \fB-raw_out\fR flag
must be used with this option, because the IHead format only supports
interleaved color pixels.  (See INTERLEAVE OPTIONS below.)
.TP
\fB-version
\fRPrint ANSI/NIST stardand and NBIS software version.

.SH INTERLEAVE OPTIONS
For example, given an RGB image, its color
components may be interleaved or non-interleaved.  Color components are
interleaved when a pixel's (R)ed, (G)reen, and (B)lue components are
sequentially adjacent in the image byte stream, ie. RGBRGBRGB... .
If the color components are non-interleaved, then all (R)ed components
in the image are sequentially adjacent in the image byte stream, followed
by all (G)reen components, and then lastly followed by all (B)lue
components.  Each complete sequence of color components is called
a \fIplane\fR.  The utilities \fBintr2not\fR and \fBnot2intr\fR
convert between interleaved and non-interleaved color components.
By default, \fBdjpegb\fR uses interleaved
color component pixels in the reconstructed output image.
Note that all color IHead images must be interleaved.

.SH NISTCOM OUTPUT
Upon successful completion, \fBdjpegb\fR, creates a specially
formatted text file called a NISTCOM file.
A NISTCOM is a text-based attribute list comprised
of (name, value) pairs, one pair per text line.
The first line of a NISTCOM always has name = "NIST_COM" 
and its value is always the total number of attributes included in
the list.  These attributes are collected and merged from two
different sources to represent the history and condition of
the resulting reconstructed image.  The first source is from an
optional NISTCOM comment block inside the JPEGB-encoded input file.
This comment block can be used to hold user-supplied attributes.
The JPEGB encoder, \fBcjpegb\fR, by convention inserts one of these
comment blocks in each compressed output file it creates.
(The utility \fBrdjpgcom\fR can be used to scan a JPEG file for
any and all comment blocks.)
The second source of attributes comes from the decompression
process itself.  In general, attribute values from this second
source are given precedence over those from the first.

The NISTCOM output filename is constructed by combining the
basename of the input JPEGB file with the extension ".ncm".
By creating the NISTCOM file, relevant attributes associated
with the decoded and reconstructed image are retained and
easily accessed.  This is especially useful when dealing with
raw pixmap files and creating image archives.  The following
is an example NISTCOM generated by \fBdjpegb\fR:

.RS
NIST_COM 10
.br
PIX_WIDTH 768
.br
PIX_HEIGHT 1024
.br
PIX_DEPTH 24
.br
PPI -1
.br
LOSSY 1
.br
COLORSPACE RGB
.br
NUM_COMPONENTS 3
.br
HV_FACTORS 1,1:1,1:1,1
.br
INTERLEAVE 1

.SH EXAMPLES
From \fItest/imgtools/execs/djpegb/djpegb.src\fR:
.PP
.RS
.B % djpegb raw face24.jpb -r
.br
decompresses a JPEGB-encoded RGB face image and stores
the reconstructed image to a raw pixmap file.  Note the
NISTCOM file, \fBface24.ncm\fR, is also created.

.SH SEE ALSO
.BR cjpegb (1G),
.BR dpyimage (1G),
.BR intr2not (1G),
.BR jpegtran (1H),
.BR not2intr (1G),
.BR rdjpgcom (1H),
.BR wrjpgcom (1H)

.SH AUTHOR
NIST/ITL/DIV894/Image Group
