.\" @(#)djpeglsd.1 2008/10/02 NIST
.\" I Image Group
.\" Craig Watson and Michael D. Garris
.\"
.TH DJPEGLSD 1G "02 October 2008" "NIST" "NBIS Reference Manual"
.SH NAME
djpeglsd \- decompresses a grayscale image that was compressed
using the old Lossless JPEG compression distributed with Special
Databases 4, 9, 10, and 18. \fBCjpegl\fR should be used in the
future to Lossless JPEG (JPEGL) compress images.
.SH SYNOPSIS
.B djpeglsd
.I <outext>
.I <image file>
.RS 7
[\fB-sd #\fR] [\fB-raw_out\fR]

.SH DESCRIPTION
.B Djpeglsd
takes as input a file containing a grayscale image that was compressed
with the old Lossless JPEG (JPEGLSD).  Specifically the version that
is included on the CDROMs with Special Databases 4, 9, 10, and 18.
Once read into memory, the compressed pixmap is decoded
and reconstructed to its original condition prior to compression.
\fBCjpegl\fR should be used for any future Lossless JPEG compression
of images.

Upon completion, two different output image file formats are possible,
a NIST IHead file (the default) or a raw pixmap file (specified by the
\fB-raw_out\fR flag).  In addition, a specially formatted text
file, called a NISTCOM, is created with extension ".ncm".  The NISTCOM
file contains relevant image attributes associated with the decoded
and reconstructed output image. If given a special database number,
\fBdjpeglsd\fR will put all the important class, sex, age, and file
history information, that may exist for that database, in the NISTCOM
file.
(See NISTCOM OUTPUT below.)

.SH OPTIONS
All switch names may be abbreviated; for example,
\fB-raw_out\fR may be written \fB-r\fR.
.TP
.I <outext>
the extension of the decompressed output file.
To construct the output filename, \fBdjpeglsd\fR takes the
input filename and replaces its extension with the one
specified here.
.TP
.I <image file>
the input JPEGLSD file to be decompressed.
.TP
.B -sd #
Specify that the input image is from NIST Special Database #.
.TP
.B -raw_out
specifies that the decoded and reconstructed image should be
stored to a raw pixmap file.
.TP
\fB-version
\fRPrint ANSI/NIST stardand and NBIS software version.

.SH NISTCOM OUTPUT
Upon successful completion, \fBdjpeglsd\fR, creates a specially
formatted text file called a NISTCOM file.
A NISTCOM is a text-based attribute list comprised
of (name, value) pairs, one pair per text line.
The first line of a NISTCOM always has name = "NIST_COM" 
and its value is always the total number of attributes included in
the list. These attributes are collected from information
about the decompressed image. Detailed attributes are
collected if the \fI-sd #\fR flag is used.

The NISTCOM output filename is constructed by combining the
basename of the input JPEGLSD file with the extension ".ncm".
By creating the NISTCOM file, relevant attributes associated
with the decoded and reconstructed image are retained and
easily accessed.  This is especially useful when dealing with
raw pixmap files and creating image archives.  The following
are example NISTCOMs generated by \fBdjpeglsd\fR for SD9 and
SD18 images (The highlighted items are attributes specific to
that database.):

.RS
NIST_COM 12
.br
.B SD_ID 9
.br
.B HISTORY f0000771.pct ac/dm_fpw:20 tape9.n1125012.01 4096x1536
.br
.B FING_CLASS W
.br
.B SEX f
.br
.B SCAN_TYPE i
.br
PIX_WIDTH 832
.br
PIX_HEIGHT 768
.br
PIX_DEPTH 8
.br
PPI 500
.br
LOSSY 0
.br
COLORSPACE GRAY
.br
.br

NIST_COM 12
.br
.B SD_ID 18
.br
.B HISTORY f00117_1.pct
.br
.B SEX m
.br
.B AGE 26
.br
.B FACE_POS f
.br
PIX_WIDTH 592
.br
PIX_HEIGHT 448
.br
PIX_DEPTH 8
.br
PPI 500
.br
LOSSY 0
.br
COLORSPACE GRAY
.br

.SH EXAMPLES
From \fItest/imgtools/execs/djpeglsd/djpeglsd.src\fR:
.RS
.PP
.B % djpeglsd raw sd04.old -sd 4  -r
.br
.B % djpeglsd raw sd09.old -sd 9  -r
.br
.B % djpeglsd raw sd10.old -sd 10 -r
.br
.B % djpeglsd raw sd18.old -sd 18 -r
.br
decompresses JPEGLSD-encoded images from the Special Databases
and stores the reconstructed images to a raw pixmap files.  Note the
NISTCOM files, \fBsd04.ncm\fR, \fBsd09.ncm\fR, \fBsd10.ncm\fR, and
\fBsd18.ncm\fR, are also created.

.SH SEE ALSO
.BR cjpegl (1G),
.BR djpegl (1G),
.BR dpyimage (1G),

.SH AUTHOR
NIST/ITL/DIV894/Image Group
