.\" @(#)dwsq.1 2008/10/02 NIST
.\" I Image Group
.\" Craig Watson and Michael D. Garris
.\"
.TH DWSQ 1G "02 October 2008" "NIST" "NBIS Reference Manual"
.SH NAME
dwsq \- decompresses a WSQ-encoded grayscale fingerprint image.
.SH SYNOPSIS
.B dwsq
.I <outext>
.I <image file>
[\fB-raw_out\fR]

.SH DESCRIPTION
.B Dwsq
takes as input a file containing a WSQ-compressed grayscale fingerprint
image.  Once read into memory, the lossy-compressed pixmap is decoded
and reconstructed using Wavelet Scalar Quantization as described in the
FBI's Criminal Justice Information Services (CJIS) document,
"WSQ Gray-scale Fingerprint Compressions Specification," Dec. 1997.
This is the only fingerprint compression format accepted by the FBI IAFIS
system.

Upon completion, two different output image file formats are possible,
a NIST IHead file (the default) or a raw pixmap file (specified by the
\fB-raw_out\fR flag).  In addition, a specially formatted text
file, called a NISTCOM, is created with extension ".ncm".  The NISTCOM
file contains relevant image attributes associated with the decoded
and reconstructed output image.
(See NISTCOM OUTPUT below.)

.SH OPTIONS
All switch names may be abbreviated; for example,
\fB-raw_out\fR may be written \fB-r\fR.
.TP
.I <outext>
the extension of the decompressed output file.
To construct the output filename, \fBdwsq\fR takes the
input filename and replaces its extension with the one
specified here.
.TP
.I <image file>
the input WSQ file to be decompressed.
.TP
.B -raw_out
specifies that the decoded and reconstructed image should be
stored to a raw pixmap file.
.TP
\fB-version
\fRPrint ANSI/NIST stardand and NBIS software version.

.SH NISTCOM OUTPUT
Upon successful completion, \fBdwsq\fR, creates a specially
formatted text file called a NISTCOM file.
A NISTCOM is a text-based attribute list comprised
of (name, value) pairs, one pair per text line.
The first line of a NISTCOM always has name = "NIST_COM" 
and its value is always the total number of attributes included in
the list.  These attributes are collected and merged from two
different sources to represent the history and condition of
the resulting reconstructed image.  The first source is from an
optional NISTCOM comment block inside the WSQ-encoded input file.
This comment block can be used to hold user-supplied attributes.
The WSQ encoder, \fBcwsq\fR, by convention inserts one of these
comment blocks in each compressed output file it creates.
(The utility \fBrdwsqcom\fR can be used to scan a WSQ file for
any and all comment blocks.)
The second source of attributes comes from the decompression
process itself.  In general, attribute values from this second
source are given precedence over those from the first.

The NISTCOM output filename is constructed by combining the
basename of the input WSQ file with the extension ".ncm".
By creating the NISTCOM file, relevant attributes associated
with the decoded and reconstructed image are retained and
easily accessed.  This is especially useful when dealing with
raw pixmap files and creating image archives.  The following
is an example NISTCOM generated by \fBdwsq\fR:

.RS
NIST_COM 7
.br
PIX_WIDTH 500
.br
PIX_HEIGHT 500
.br
PIX_DEPTH 8
.br
PPI 500
.br
LOSSY 1
.br
COLORSPACE GRAY

.SH EXAMPLES
From \fItest/imgtools/execs/dwsq/dwsq.src\fR:
.PP
.RS
.B % dwsq raw finger.wsq -r
.br
decompresses a WSQ-encoded fingerprint image and stores
the reconstructed image to a raw pixmap file.  Note the
NISTCOM file, \fBfinger.ncm\fR, is also created.

.SH SEE ALSO
.BR cwsq (1G),
.BR dpyimage (1G),
.BR rdwsqcom (1G),
.BR wrwsqcom (1G)

.SH AUTHOR
NIST/ITL/DIV894/Image Group
