.\" @(#)dwsq14.1 2008/10/02 NIST
.\" I Image Group
.\" Craig Watson and Michael D. Garris
.\"
.TH DWSQ14 1G "02 October 2008" "NIST" "NBIS Reference Manual"
.SH NAME
dwsq14 \- decompresses a WSQ14-encoded grayscale fingerprint image from
NIST Special Database 14.
.SH SYNOPSIS
.B dwsq14
.I <outext>
.I <image file>
[\fB-raw_out\fR]

.SH DESCRIPTION
.B Dwsq14
takes as input a file containing a WSQ14-compressed grayscale fingerprint
image from NIST Special Database 14.  The version of WSQ14 used to compress
the images on this database is not certified and produces loss that may
be more than permitted by a certified WSQ compression algorithm.  Once
read into memory, the lossy-compressed pixmap is decoded and reconstructed
using Wavelet Scalar Quantization as described in the FBI's Criminal
Justice Information Services (CJIS) document, "WSQ Gray-scale Fingerprint
Compressions Specification," Dec. 1997.  This is the only fingerprint
compression format accepted by the FBI IAFIS system.

Upon completion, two different output image file formats are possible,
a NIST IHead file (the default) or a raw pixmap file (specified by the
\fB-raw_out\fR flag).  In addition, a specially formatted text
file, called a NISTCOM, is created with extension ".ncm".  The NISTCOM
file contains relevant image attributes associated with the decoded
and reconstructed output image.
(See NISTCOM OUTPUT below.)

.SH OPTIONS
All switch names may be abbreviated; for example,
\fB-raw_out\fR may be written \fB-r\fR.
.TP
.I <outext>
the extension of the decompressed output file.
To construct the output filename, \fBdwsq14\fR takes the
input filename and replaces its extension with the one
specified here.
.TP
.I <image file>
the input WSQ14 file to be decompressed.
.TP
.B -raw_out
specifies that the decoded and reconstructed image should be
stored to a raw pixmap file.
.TP
\fB-version
\fRPrint ANSI/NIST stardand and NBIS software version.

.SH NISTCOM OUTPUT
Upon successful completion, \fBdwsq14\fR, creates a specially
formatted text file called a NISTCOM file.
A NISTCOM is a text-based attribute list comprised
of (name, value) pairs, one pair per text line.
The first line of a NISTCOM always has name = "NIST_COM" 
and its value is always the total number of attributes included in
the list.  These attributes are collected from two sources
and merged to represent the history and condition of the resulting
reconstructed image.  The two sources for the attributes are the
IHEAD header of the compressed image (specific information
about the fingerprint itself is contained here) and the
decompression process.  In general, attribute values from the second
source are given precedence over those from the first.

The NISTCOM output filename is constructed by combining the
basename of the input WSQ14 file with the extension ".ncm".
By creating the NISTCOM file, relevant attributes associated
with the decoded and reconstructed image are retained and
easily accessed.  This is especially useful when dealing with
raw pixmap files and creating image archives.  The following
is an example NISTCOM generated by \fBdwsq14\fR (highlighted
items specific to SD14):

.RS
NIST_COM 12
.br
PPI 500
.br
.B SD_ID 14
.br
.B HISTORY f0000001.wsq 20 tape3.t1116010.01 4096x1536
.br
.B FING_CLASS R
.br
.B SEX m
.br
.B SCAN_TYPE i
.br
PIX_WIDTH 832
.br
PIX_HEIGHT 768
.br
PIX_DEPTH 8
.br
LOSSY 1
.br
COLORSPACE GRAY

.SH EXAMPLES
From \fItest/imgtools/execs/dwsq14/dwsq14.src\fR:
.PP
.RS
.B % dwsq14 raw sd14.old -r
.br
decompresses a WSQ14-encoded fingerprint image and stores
the reconstructed image to a raw pixmap file.  Note the
NISTCOM file, \fBsd14.ncm\fR, is also created.

.SH SEE ALSO
.BR cwsq (1G),
.BR dwsq (1G),
.BR dpyimage (1G),

.SH AUTHOR
NIST/ITL/DIV894/Image Group
